/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;
 
/**
 *
 * @author anggy
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lanjut = new javax.swing.JLabel();
        lanjut1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lanjut.png"))); // NOI18N
        lanjut.setText("lanjut");
        lanjut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lanjutMouseExited(evt);
            }
        });
        getContentPane().add(lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 140, 110));

        lanjut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lanjut1.png"))); // NOI18N
        lanjut1.setText("jLabel2");
        lanjut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lanjut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lanjut1MouseClicked(evt);
            }
        });
        getContentPane().add(lanjut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 140, 130));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/splash.png"))); // NOI18N
        background.setText("background");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanjutMouseEntered
        lanjut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lanjutMouseEntered

    private void lanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanjutMouseExited
        lanjut.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_lanjutMouseExited

    private void lanjut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanjut1MouseClicked
        ayam.view.utama v = new ayam.view.utama();
        ayam.Controller.utama c = new ayam.Controller.utama(v);
        setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_lanjut1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new dashboard().setVisible(true);
////            }
////        });
//  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel lanjut;
    private javax.swing.JLabel lanjut1;
    // End of variables declaration//GEN-END:variables
}
