/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anggy
 */
public class infoObat extends javax.swing.JFrame {

    /**
     * Creates new form infoObat
     */
    public infoObat() {
        this.setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }
       
    public void kembali(ActionListener listener1) {
        kembali.addActionListener(listener1);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kembali = new javax.swing.JButton();
        kembali2 = new javax.swing.JLabel();
        kembali3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-kembali-1.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 90, 30));

        kembali2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembali2MouseClicked(evt);
            }
        });
        getContentPane().add(kembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 20, 30));

        kembali3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembali3MouseClicked(evt);
            }
        });
        getContentPane().add(kembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, 20, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/info obat 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
//        String minggu = "0";
//        try {
//            ayam.view.ObatView v = new ayam.view.ObatView();
//
//            ayam.Model.OBAT m = new ayam.Model.OBAT();
//
//            ayam.Controller.Obat c = new ayam.Controller.Obat(v, m, minggu);
//
//            this.setVisible(false);
//            // TODO add your handling code here:
//        } catch (SQLException ex) {
//            Logger.getLogger(infoObat.class.getName()).log(Level.SEVERE, null, ex);
//        }


    }//GEN-LAST:event_kembaliActionPerformed

    private void kembali2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembali2MouseClicked
        new infoObat2().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_kembali2MouseClicked

    private void kembali3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembali3MouseClicked
        new infoObat3().setVisible(true);
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_kembali3MouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
//        try {
//            ayam.view.sakit v = new ayam.view.sakit();
//            ayam.Model.AYAM m = new ayam.Model.AYAM();
//            String minggu = null;
//            ayam.Controller.Ayam c = new ayam.Controller.Ayam(v, m, minggu);// TODO add your handling code here:
//        } catch (SQLException ex) {
//            Logger.getLogger(infoObat.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoObat().setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel kembali2;
    private javax.swing.JLabel kembali3;
    // End of variables declaration//GEN-END:variables
}
