/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import ayam.Controller.Kandang;
import ayam.Model.KANDANG;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author anggy
 */
public class KandangView extends javax.swing.JFrame {

    ayam.Model.KANDANG ayam;
    String[][] kandang;

    public KandangView() throws SQLException {
        ayam = new KANDANG();
        tipeKandang = new JComboBox();
        kandang = ayam.getKandang();
        initComponents();
        this.setLocationRelativeTo(null);

    }
     public void setModal(String modal) {
        this.modal.setText(modal);
    }

    public String getModal() {
        return modal.getText();
    }

    public void clearInput() {
        jumlah.setText("");
        harga.setText("");
        ukuran.setText("");
    }

    public String getKandang() {
        return tipeKandang.getSelectedItem().toString();
    }

    public String getKandang1() {
        int a = tipeKandang.getSelectedIndex();
        System.out.println("woooooooyyyyyy " + kandang[0][a]);
        return kandang[0][a];

    }

    public String getUkuran() {
        return ukuran.getText();
    }

    public String getJumlahAyam() {
        return jumlahAyam.getText();
    }
//     public String getFasilitas() {
//        return fasilitas.getText();
//    }

    public String getHarga() {
        return harga.getText();
    }

    public String getJumlah() {
        return jumlah.getText();
    }

    public void setUkuran(String Ukuran) {
        this.ukuran.setText(Ukuran);
    }

    public void setJumlahAyam(String JumlahAyam) {
        this.jumlahAyam.setText(JumlahAyam);
    }
//    public void setfasilitas(String fasilitas) {
//        this.fasilitas.setText(fasilitas);
//    }

    public void setharga(String harga) {
        this.harga.setText(harga);
    }

    public void setjumlah(String jumlah) {
        this.jumlah.setText(jumlah);
    }

    public void addbeliListener(ActionListener listener) {
        beli.addActionListener(listener);

    }

    public void addrincianListener(ActionListener listener) {
        rincian.addActionListener(listener);

    }

    public void addpilihListener(ActionListener listener) {
        tipeKandang.addActionListener(listener);
    }

    public void addkembali(ActionListener listener) {
        kembali.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jumlah = new javax.swing.JTextField();
        tipeKandang = new javax.swing.JComboBox(kandang[1]);
        kembali = new javax.swing.JButton();
        ukuran = new javax.swing.JLabel();
        jumlahAyam = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        rincian = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        modal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jumlah.setBorder(null);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 120, 40));

        getContentPane().add(tipeKandang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 130, 40));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-kembali-1.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 90, 30));
        getContentPane().add(ukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, 40));
        getContentPane().add(jumlahAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 90, 40));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 100, 40));

        beli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button beli 1.png"))); // NOI18N
        beli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 90, 30));

        rincian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button rincian 1.png"))); // NOI18N
        rincian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(rincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 90, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-info-1.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 100, 30));

        modal.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        getContentPane().add(modal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian kandang.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
//        try {
//            String minggu = "0";
//            ayam.view.pembelian v = new ayam.view.pembelian();
//             ayam.Model.AYAM m = new ayam.Model.AYAM();
//            ayam.Controller.pembelian c = new ayam.Controller.pembelian(v,m, minggu);
//            this.setVisible(false);// TODO add your handling code here:
//        } catch (SQLException ex) {
//            Logger.getLogger(KandangView.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_kembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new infoKandang().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        char karakter = evt.getKeyChar();
        if (!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KandangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KandangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KandangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KandangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KandangView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(KandangView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton beli;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JLabel jumlahAyam;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel modal;
    private javax.swing.JButton rincian;
    private javax.swing.JComboBox tipeKandang;
    private javax.swing.JLabel ukuran;
    // End of variables declaration//GEN-END:variables

}
