/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import ayam.Controller.Obat;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import javax.swing.JComboBox;
import ayam.Model.OBAT;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anggy
 */
public class ObatView extends javax.swing.JFrame {
    
    ayam.Model.OBAT ayam;
    String[][] obat;
    String keterangan;
    String aturan;
    
    public ObatView() throws SQLException {
        ayam = new OBAT();
        namaObat = new JComboBox();
        obat = ayam.getObat();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void clearInput() {
        jumlah.setText("");
        harga.setText("");
        rincian.setText("");
    }

    public String getObat() {
        return namaObat.getSelectedItem().toString();
    }
    
    public String getObat1() {
        int a = namaObat.getSelectedIndex();
        System.out.println("woooooooyyyyyy " + obat[0][a]);
        return obat[0][a];
    }
    
    public String getKeterangan() {
        return keterangan;
    }
    
    public String getRincian() {
        return rincian.getText();
    }
    
    public String getAturanPakai() {
        return aturan;
    }
    
    public String getHarga() {
        return harga.getText();
    }
    
    public String getJumlah() {
        return jumlah.getText();
    }
    
    public void setketerangan(String ket) {
        this.keterangan = ket;
    }
    
    public void setAturan(String ket) {
        this.aturan = ket;
    }
    
    public void setrincian(String rincian) {
        this.rincian.setText(rincian);
    }

//    public void setaturan(String aturan) {
//        this.aturan.setText(aturan);
//    }
    public void setharga(String harga) {
        this.harga.setText(harga);
    }
    
    public void setjumlah(String jumlah) {
        this.jumlah.setText(jumlah);
    }
    
    public String getjumlah() {
        return jumlah.getText();
    }
    
    public void addbeliListener(ActionListener listener) {
        beli.addActionListener(listener);
        
    }
    
    public void addrincianListener1(ActionListener listener1) {
        rincian1.addActionListener(listener1);
        
    }
    
    public void addpilihListener(ActionListener listener) {
        namaObat.addActionListener(listener);
    }
    
    public void addKembaliListener(ActionListener listener) {
        kembali.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kembali = new javax.swing.JButton();
        rincian = new javax.swing.JLabel();
        namaObat = new javax.swing.JComboBox(obat[1]);
        harga = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        rincian1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-kembali-1.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 90, 30));
        getContentPane().add(rincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 110, 40));

        getContentPane().add(namaObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 130, 40));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, 40));

        beli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button beli 1.png"))); // NOI18N
        beli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 90, 30));

        jumlah.setBorder(null);
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 120, 40));

        rincian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button rincian 1.png"))); // NOI18N
        rincian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(rincian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 90, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-info-1.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 100, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian-obat.jpg"))); // NOI18N
        back.setText("jLabel1");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        //String minggu = "0";
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new infoKandang().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new infoObat().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
char karakter = evt.getKeyChar();
if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
    getToolkit().beep();
    evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ObatView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ObatView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton beli;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox namaObat;
    private javax.swing.JLabel rincian;
    private javax.swing.JButton rincian1;
    // End of variables declaration//GEN-END:variables

}
