/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import ayam.Controller.Pakan;
import ayam.Model.PAKAN;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author anggy
 */
public class PakanView extends javax.swing.JFrame {

    ayam.Model.PAKAN ayam;
    String[][] pakan;
    String keterangan;
    String komposisi;
    String minggu;

    public PakanView() throws SQLException {
        ayam = new PAKAN();
        jenisPakan = new JComboBox();
        pakan = ayam.getPakan3();
        initComponents();
        this.setLocationRelativeTo(null);
    }
      public void setModal(String modal) {
        this.modal.setText(modal);
    }

    public String getModal() {
        return modal.getText();
    }

    public void clearInput() {
        jumlah.setText("");
        harga.setText("");
        efek.setText("");
    }

    public PakanView(String s) throws SQLException {
        ayam = new PAKAN();
        jenisPakan = new JComboBox();
        pakan = ayam.getPakan3();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public String getPakan1() {
        int a = jenisPakan.getSelectedIndex();
        System.out.println("woooooooyyyyyy " + pakan[0][a]);
        return pakan[0][a];

    }

    public String getPakan() {
        return jenisPakan.getSelectedItem().toString();
    }
//     public String getPakan1() {
//        return jenisPakan.getSelectedItem().toString();
//    }

    public String getEfek() {
        return efek.getText();
    }

    public String getHarga() {
        return harga.getText();
    }

    public String getKeterangan() {
        return keterangan;
    }

    public String getKomposisi() {
        return komposisi;
    }

    public String getJumlah() {
        return jumlah.getText();
    }

    public void setefek(String efek) {
        this.efek.setText(efek);
    }

    public void setKeterangan(String efek) {
        this.keterangan = efek;
    }

    public void setKomposisi(String efek) {
        this.komposisi = efek;
    }

    public void setMinggu(String efek) {
        this.minggu = efek;
    }

    public void setharga(String harga) {
        this.harga.setText(harga);
    }

    public void setjumlah(String jumlah) {
        this.jumlah.setText(jumlah);
    }

    public void addbeliListener(ActionListener listener) {
        beli.addActionListener(listener);
    }

    public void addrincianListener(ActionListener listener) {
        rincian.addActionListener(listener);
    }

    public void addpilihListener(ActionListener listener) {
        jenisPakan.addActionListener(listener);
    }
    public void addkembali(ActionListener listener) {
        kembali.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        harga = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        efek = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jenisPakan = new javax.swing.JComboBox(pakan[1]);
        rincian = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        modal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 100, 40));

        beli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button beli 1.png"))); // NOI18N
        beli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 90, 30));

        jumlah.setBorder(null);
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 120, 40));
        getContentPane().add(efek, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 90, 40));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-kembali-1.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 90, 30));
        getContentPane().add(jenisPakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 130, 40));

        rincian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button rincian 1.png"))); // NOI18N
        rincian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(rincian, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 90, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-info-1.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 100, 30));

        modal.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        getContentPane().add(modal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Uang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian pakan.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
//        try {
//            ayam.view.pembelian v = new ayam.view.pembelian();
//             ayam.Model.AYAM m = new ayam.Model.AYAM();
//            ayam.Controller.pembelian c = new ayam.Controller.pembelian(v,m, minggu);
//            this.setVisible(false);// TODO add your handling code here:
//        } catch (SQLException ex) {
//            Logger.getLogger(PakanView.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_kembaliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new infoPakan1().setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
char karakter = evt.getKeyChar();
if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
    getToolkit().beep();
    evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PakanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PakanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PakanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PakanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PakanView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PakanView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton beli;
    private javax.swing.JLabel efek;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jenisPakan;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel modal;
    private javax.swing.JButton rincian;
    // End of variables declaration//GEN-END:variables

}
