/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anggy
 */
public class perawatan extends javax.swing.JFrame {

    /**
     * Creates new form perawatan
     */
    public perawatan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void addperawatan(ActionListener Listener) {
        minggu1.addActionListener(Listener);
    }
    public void addperawatan2(ActionListener Listener) {
        minggu2.addActionListener(Listener);
    }
     public void addperawatan3(ActionListener Listener) {
        minggu3.addActionListener(Listener);
    }
      public void addperawatan4(ActionListener Listener) {
        minggu4.addActionListener(Listener);
    }
      public void kembali(ActionListener Listener) {
        kembali.addActionListener(Listener);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minggu1 = new javax.swing.JButton();
        minggu2 = new javax.swing.JButton();
        minggu3 = new javax.swing.JButton();
        minggu4 = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minggu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button perawatan1.png"))); // NOI18N
        minggu1.setBorder(null);
        minggu1.setBorderPainted(false);
        minggu1.setContentAreaFilled(false);
        minggu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minggu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minggu1MouseClicked(evt);
            }
        });
        getContentPane().add(minggu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 100, 90));

        minggu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button perawatan2.png"))); // NOI18N
        minggu2.setBorderPainted(false);
        minggu2.setContentAreaFilled(false);
        getContentPane().add(minggu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 120, 120));

        minggu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button perawatan3.png"))); // NOI18N
        minggu3.setBorderPainted(false);
        minggu3.setContentAreaFilled(false);
        getContentPane().add(minggu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 140, 130));

        minggu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button perawatan4.png"))); // NOI18N
        minggu4.setBorderPainted(false);
        minggu4.setContentAreaFilled(false);
        minggu4.setDefaultCapable(false);
        getContentPane().add(minggu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 160, 150));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-kembali-1.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg-tampilan-awal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minggu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minggu1MouseClicked
       
        
        
    }//GEN-LAST:event_minggu1MouseClicked

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        //        String minggu = "0";
        //        try {
            //            ayam.view.ObatView v = new ayam.view.ObatView();
            //
            //            ayam.Model.OBAT m = new ayam.Model.OBAT();
            //
            //            ayam.Controller.Obat c = new ayam.Controller.Obat(v, m, minggu);
            //
            //            this.setVisible(false);
            //            // TODO add your handling code here:
            //        } catch (SQLException ex) {
            //            Logger.getLogger(infoObat.class.getName()).log(Level.SEVERE, null, ex);
            //        }

    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perawatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perawatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perawatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perawatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perawatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton minggu1;
    private javax.swing.JButton minggu2;
    private javax.swing.JButton minggu3;
    private javax.swing.JButton minggu4;
    // End of variables declaration//GEN-END:variables
}
