/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anggy
 */
public class rincian_ayam extends javax.swing.JFrame {

    /**
     * Creates new form rincian_ayam
     */
    public rincian_ayam() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JTable getTabel() {
        return tabel;
    }

    public String getModal() {
        return modal.getText();
    }

    public void setModal(String modal) {
        this.modal.setText(modal);
    }
//    public String getjumlah() {
//        return jumlah.getText();
//    }

    public int getSelectedRow() {
        int baris = tabel.getSelectedRow();
        return baris;
    }

//    public void setjumlah(String jumlah) {
//        this.jumlah.setText(jumlah);
//    }
//    public void addubahListener(ActionListener listener) {
//        ubah.addActionListener(listener);
//    }
    public void addhapusListener(ActionListener listener) {
        hapus.addActionListener(listener);
    }
//    public void addtambahListener(ActionListener listener) {
//        beli.addActionListener(listener);
//    }

    public String getidAyam() {
        return idAyam.getText();
    }

    public void setTableModel(DefaultTableModel tm) {
        tabel.setModel(tm);
    }

    public void enableEditAndDelete() {
        //      ubah.setEnabled(true);
        hapus.setEnabled(true);
    }

    public void disableEditAndDelete() {
        //     ubah.setEnabled(false);
        hapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        idAyam = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        modal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 440, 400));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-hapus.png"))); // NOI18N
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 90, 30));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-kembali-1.png"))); // NOI18N
        kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 90, 30));
        getContentPane().add(idAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 50, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rincian-pembelian-ayam.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
        getContentPane().add(modal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        try {
            ayam.view.AyamView v = new ayam.view.AyamView();
            ayam.Model.AYAM m = new ayam.Model.AYAM();
            ayam.Controller.Ayam c = new ayam.Controller.Ayam(v, m);// TODO add your handling code here:
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(rincian_ayam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rincian_ayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rincian_ayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rincian_ayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rincian_ayam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rincian_ayam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel idAyam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel modal;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
