 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import ayam.Model.OBAT;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anggy
 */
public class sakit extends javax.swing.JFrame {

    ayam.Model.OBAT ayam;
    String[][] obat;
    String keterangan;
    String aturan;

    public sakit() {
        try {
            ayam = new OBAT();
        } catch (SQLException ex) {
            Logger.getLogger(sakit.class.getName()).log(Level.SEVERE, null, ex);
        }
        namaObat = new JComboBox();
        try {
            obat = ayam.getObat();
        } catch (SQLException ex) {
            Logger.getLogger(sakit.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public String getObat1() {
        int a= namaObat.getSelectedIndex();
         System.out.println("woooooooyyyyyy " + obat[0][a]);
         return obat[0][a];
    }
    
    public void klikKembali(ActionListener listener) {
        kembali.addActionListener(listener);
    }

//    public void klikBeliObat(ActionListener listener) {
//        beli.addActionListener(listener);
//    }

    public void setTableModel(DefaultTableModel ts) {
        tabel.setModel(ts);
    }
    
    public void setJumlahAyam (String teks){
        jumlahAyam.setText(teks);
    }
    
    public void setSakit (String teks){
        sakit.setText(teks);
    }
    
    public String getJumlahAyam() {
        return jumlahAyam.getText();
    }

    public String getSakit() {
        return sakit.getText();
    }

    public String getObat() {
        return namaObat.getSelectedItem().toString();
    }

    public String getJumlah() {
        return jumlah.getText();
    }
    public String getHarga() {
        return harga.getText();
    }

    public void disableEditAndDelete() {
        jumlahAyam.setEnabled(false);
        sakit.setEnabled(false);
    }

    public void clearInput() {
        jumlah.setText("");

    }

    public void addbeliListener(ActionListener listener) {
        beli.addActionListener(listener);
        System.out.println("ayuuuuyuuuuyuyuuu");

    }

    public void addrincianListener1(ActionListener listener1) {
        rincian1.addActionListener(listener1);

    }

    public void kembali(ActionListener listener1) {
        kembali.addActionListener(listener1);

    }
    public void addInfo(ActionListener listener1) {
        info.addActionListener(listener1);

    }

    public void addpilihListener(ActionListener listener) {
        namaObat.addActionListener(listener);
    }

    public int getSelectedRow() {
        int baris = tabel.getSelectedRow();
        return baris;
    }

    public void addTableListener(MouseListener listener) {
        tabel.addMouseListener(listener);
    }
    
    public void tabelSakit (MouseListener a){
        tabel.addMouseListener(a);
    }
    
    public JTable getTabel(){
        return tabel;
    }

    public void addubahListener(ActionListener listener) {
        //      ubah.addActionListener(listener);
    }

    public void addtambahListener(ActionListener listener) {
        //       tambah.addActionListener(listener);
    }

    public void addhapusListener(ActionListener listener) {
        //     hapus.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        kembali = new javax.swing.JButton();
        beli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jumlahAyam = new javax.swing.JTextField();
        sakit = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        rincian1 = new javax.swing.JButton();
        info = new javax.swing.JButton();
        namaObat = new javax.swing.JComboBox(obat[1]);
        harga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayam/view/button-kembali-1.png"))); // NOI18N
        kembali.setBorder(null);
        kembali.setContentAreaFilled(false);
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 100, 30));

        beli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button beli 1.png"))); // NOI18N
        beli.setContentAreaFilled(false);
        beli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beliMouseClicked(evt);
            }
        });
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 100, 30));

        jLabel2.setText("Jumlah Ayam");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jLabel3.setText("Jumlah Beli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));
        getContentPane().add(jumlahAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 50, 20));
        getContentPane().add(sakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 120, 30));

        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 100, 30));

        rincian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button rincian 1.png"))); // NOI18N
        rincian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(rincian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 90, 30));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button-info-1.png"))); // NOI18N
        info.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 100, 30));

        getContentPane().add(namaObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 130, 40));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 60, 20));

        jLabel4.setText("Sakit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel5.setText("Jenis Obat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayam/view/tampilan-perawatan-sakit.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked

    }//GEN-LAST:event_kembaliMouseClicked

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beliActionPerformed

    private void beliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliMouseClicked
//        try {
//            String minggu = "1";
//            ayam.view.sakit v = new ayam.view.sakit();
//            ayam.Model.OBAT m = new ayam.Model.OBAT();
//            ayam.Controller.Obat c = new ayam.Controller.Obat(v, m, minggu);
//            this.setVisible(false);
//        } catch (SQLException ex) {
//            Logger.getLogger(sakit.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_beliMouseClicked

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
//        new infoObat().setVisible(true);
//        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_infoMouseClicked

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
//        new infoKandang().setVisible(true);
//        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_infoActionPerformed

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
char karakter = evt.getKeyChar();
if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
    getToolkit().beep();
    evt.consume();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beli;
    private javax.swing.JLabel harga;
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField jumlahAyam;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox namaObat;
    private javax.swing.JButton rincian1;
    private javax.swing.JTextField sakit;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
