/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ayam.view;

import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author anggy
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public void pembelian(MouseListener e) {
        this.pembelian.addMouseListener(e);
    }
     public void perawatan(MouseListener e) {
        this.perawatan.addMouseListener(e);
    }
     public void penjualan(MouseListener e) {
        this.jual.addMouseListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pembelian = new javax.swing.JLabel();
        perawatan = new javax.swing.JLabel();
        jual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianMouseClicked(evt);
            }
        });
        getContentPane().add(pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 140, 130));

        perawatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perawatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perawatanMouseClicked(evt);
            }
        });
        getContentPane().add(perawatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 140, 160));

        jual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 150, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tampilan-awal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMouseClicked
//        String minggu = "0";
//        ayam.view.pembelian v = new ayam.view.pembelian();
//        ayam.Controller.pembelian c = new ayam.Controller.pembelian(v, minggu);
//        this.setVisible(false);

    }//GEN-LAST:event_pembelianMouseClicked

    private void perawatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perawatanMouseClicked
//        try {
//            this.setVisible(false);
//            ayam.view.perawatan v = new ayam.view.perawatan();
//            ayam.Model.AYAM m = new ayam.Model.AYAM();
//            ayam.Controller.perawatan c = new ayam.Controller.perawatan(v, m);
//            // TODO add your handling code here:
//        } catch (SQLException ex) {
//            Logger.getLogger(utama.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_perawatanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jual;
    private javax.swing.JLabel pembelian;
    private javax.swing.JLabel perawatan;
    // End of variables declaration//GEN-END:variables
}
